//! Outbound automation webhooks.
//!
//! The Webhooks tab used to describe a LOCAL HTTP LISTENER that was never built — and before
//! that it falsely reported "listening on localhost" while binding nothing. A listening socket
//! in a desktop app is also the wrong shape: it opens an inbound attack surface on the
//! customer's own machine and needs a port, a firewall rule and a story about who may connect.
//!
//! This module implements the direction that actually matters for this product: OUTBOUND. When
//! something real happens (a product is generated, exported or published), DPF POSTs a small
//! JSON event to a URL the user configures — Zapier, Make, n8n, their own endpoint. Nothing
//! listens, so there is no port to open and nothing for a third party to connect to.
//!
//! The signed body lets the receiver verify the event really came from this app.
//!
//! Delivery is deliberately fire-and-forget on a worker thread: a slow or dead endpoint must
//! never freeze the UI, which is the failure mode that makes webhook features feel broken.

use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::sync::Mutex;
use std::time::Duration;

type HmacSha256 = Hmac<Sha256>;

/// How long a single delivery may take before it is abandoned.
///
/// A hanging request would otherwise pin a worker thread for the OS default (minutes). Five
/// seconds is generous for a POST of a few hundred bytes and keeps a dead endpoint harmless.
const DELIVERY_TIMEOUT: Duration = Duration::from_secs(5);

/// The events a user can subscribe to. Kept as an enum so adding one is a compile-checked
/// change rather than a string that silently never fires.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebhookEvent {
    /// A product asset was generated by an AI workflow.
    ProductGenerated,
    /// An asset was written to disk in any export format.
    ProductExported,
    /// A listing was pushed to a connected marketplace.
    ProductPublished,
    /// A licence key was accepted by the app.
    LicenceActivated,
}

impl WebhookEvent {
    /// The wire name. Stable: receivers key off this string.
    pub fn as_str(&self) -> &'static str {
        match self {
            WebhookEvent::ProductGenerated => "product.generated",
            WebhookEvent::ProductExported => "product.exported",
            WebhookEvent::ProductPublished => "product.published",
            WebhookEvent::LicenceActivated => "licence.activated",
        }
    }

    /// Every event, for the settings UI and for iteration.
    pub fn all() -> [WebhookEvent; 4] {
        [
            WebhookEvent::ProductGenerated,
            WebhookEvent::ProductExported,
            WebhookEvent::ProductPublished,
            WebhookEvent::LicenceActivated,
        ]
    }

    /// Human label for the UI.
    pub fn label(&self) -> &'static str {
        match self {
            WebhookEvent::ProductGenerated => "Product generated",
            WebhookEvent::ProductExported => "Product exported",
            WebhookEvent::ProductPublished => "Listing published",
            WebhookEvent::LicenceActivated => "Licence activated",
        }
    }
}

/// One attempt at delivering one event, kept so the user can see whether it worked.
///
/// Without this the feature is unfalsifiable: the user would have no way to tell "sent" from
/// "silently dropped", which is exactly the class of dishonesty this tab is recovering from.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Delivery {
    pub event: String,
    pub url: String,
    /// Ok(http status) or Err(reason). Never contains the signing secret.
    pub result: String,
    pub ok: bool,
    /// Unix epoch seconds.
    pub at: i64,
}

/// The webhook configuration, stored with the rest of the app config.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookConfig {
    pub enabled: bool,
    pub url: String,
    /// Shared secret for the HMAC signature. Written to the local config file, like the AI keys.
    pub secret: String,
    /// Which events to send. Defaults to the three product lifecycle events.
    pub events: Vec<String>,
}

impl Default for WebhookConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            url: String::new(),
            secret: String::new(),
            events: vec![
                WebhookEvent::ProductGenerated.as_str().to_string(),
                WebhookEvent::ProductExported.as_str().to_string(),
                WebhookEvent::ProductPublished.as_str().to_string(),
            ],
        }
    }
}

/// Reasons a URL is rejected, decided BEFORE any request is made.
///
/// Returns Ok(()) when the URL is worth attempting. The check is deliberately shallow — this
/// is the user's own machine and endpoint — but it must catch a blank or scheme-less entry,
/// because `reqwest` would otherwise fail with an opaque error and look like a broken feature.
pub fn validate_url(url: &str) -> Result<(), String> {
    let u = url.trim();
    if u.is_empty() {
        return Err("no webhook URL is set".into());
    }
    if !(u.starts_with("http://") || u.starts_with("https://")) {
        return Err("the URL must start with http:// or https://".into());
    }
    // A bare scheme is not a destination.
    let rest = u.splitn(2, "://").nth(1).unwrap_or("");
    if rest.trim_matches('/').is_empty() {
        return Err("the URL has no host".into());
    }
    Ok(())
}

/// Compute the signature the receiver verifies: hex HMAC-SHA256 of the exact body bytes.
///
/// Signing the BODY (not a summary of it) is what lets the receiver detect tampering. The
/// header is `X-DPF-Signature: sha256=<hex>`, the convention receivers already expect.
pub fn sign(secret: &str, body: &[u8]) -> String {
    let mut mac = HmacSha256::new_from_slice(secret.as_bytes())
        .expect("HMAC accepts a key of any length");
    mac.update(body);
    let bytes = mac.finalize().into_bytes();
    let mut s = String::with_capacity(7 + bytes.len() * 2);
    s.push_str("sha256=");
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// The JSON body sent to the endpoint. `product` is opaque to us — callers pass whatever
/// identifying detail they have, so this module never needs to know product internals.
#[derive(Debug, Serialize)]
struct Envelope<'a> {
    event: &'a str,
    app: &'a str,
    version: &'a str,
    sent_at: i64,
    data: serde_json::Value,
}

/// The shared delivery log. Bounded so a long-running app cannot grow it without limit.
pub struct WebhookLog {
    entries: Mutex<Vec<Delivery>>,
}

impl Default for WebhookLog {
    fn default() -> Self {
        Self { entries: Mutex::new(Vec::new()) }
    }
}

impl WebhookLog {
    const MAX: usize = 50;

    pub fn record(&self, d: Delivery) {
        if let Ok(mut v) = self.entries.lock() {
            v.insert(0, d);
            v.truncate(Self::MAX);
        }
    }

    /// Newest first.
    pub fn recent(&self) -> Vec<Delivery> {
        self.entries.lock().map(|v| v.clone()).unwrap_or_default()
    }

    pub fn clear(&self) {
        if let Ok(mut v) = self.entries.lock() {
            v.clear();
        }
    }
}

/// Send one event. Returns immediately; the request happens on a worker thread.
///
/// Every early return is recorded in the log, so "nothing arrived" always has a visible
/// reason in the app rather than being a silent no-op.
pub fn dispatch(cfg: &WebhookConfig, log: &std::sync::Arc<WebhookLog>, event: WebhookEvent, data: serde_json::Value) {
    if !cfg.enabled {
        return;
    }
    if !cfg.events.iter().any(|e| e == event.as_str()) {
        return;
    }
    if let Err(reason) = validate_url(&cfg.url) {
        log.record(Delivery {
            event: event.as_str().into(),
            url: cfg.url.clone(),
            result: format!("not sent: {reason}"),
            ok: false,
            at: now(),
        });
        return;
    }

    let url = cfg.url.trim().to_string();
    let secret = cfg.secret.clone();
    let log = log.clone();

    let body = match serde_json::to_vec(&Envelope {
        event: event.as_str(),
        app: "Digital Product Factory",
        version: env!("CARGO_PKG_VERSION"),
        sent_at: now(),
        data,
    }) {
        Ok(b) => b,
        Err(e) => {
            log.record(Delivery {
                event: event.as_str().into(),
                url,
                result: format!("could not build the payload: {e}"),
                ok: false,
                at: now(),
            });
            return;
        }
    };

    std::thread::spawn(move || {
        let client = match reqwest::blocking::Client::builder()
            .timeout(DELIVERY_TIMEOUT)
            .build()
        {
            Ok(c) => c,
            Err(e) => {
                log.record(Delivery {
                    event: event.as_str().into(),
                    url,
                    result: format!("could not start the request: {e}"),
                    ok: false,
                    at: now(),
                });
                return;
            }
        };

        let mut req = client
            .post(&url)
            .header("Content-Type", "application/json")
            .header("User-Agent", concat!("DigitalProductFactory/", env!("CARGO_PKG_VERSION")))
            .body(body.clone());

        // Sign only when a secret is set; an unsigned event is a legitimate choice.
        if !secret.is_empty() {
            req = req.header("X-DPF-Signature", sign(&secret, &body));
        }

        let (ok, result) = match req.send() {
            Ok(resp) => {
                let code = resp.status().as_u16();
                (resp.status().is_success(), format!("HTTP {code}"))
            }
            Err(e) => {
                // Distinguish the two failures a user can act on differently.
                let why = if e.is_timeout() {
                    format!("no response within {}s", DELIVERY_TIMEOUT.as_secs())
                } else if e.is_connect() {
                    "could not connect to that host".to_string()
                } else {
                    format!("request failed: {e}")
                };
                (false, why)
            }
        };

        log.record(Delivery { event: event.as_str().into(), url, result, ok, at: now() });
    });
}

/// Send a probe event SYNCHRONOUSLY and return a human result for the settings screen.
///
/// This is deliberately blocking, unlike `dispatch`: the user pressed a button and is waiting
/// for an answer, so the honest thing is to report the real outcome now rather than queue work
/// and claim success. It never panics and never reveals the secret.
pub fn send_test_now(cfg: &WebhookConfig) -> String {
    if let Err(e) = validate_url(&cfg.url) {
        return format!("Not sent: {e}.");
    }
    let body = match serde_json::to_vec(&Envelope {
        event: "webhook.test",
        app: "Digital Product Factory",
        version: env!("CARGO_PKG_VERSION"),
        sent_at: now(),
        data: serde_json::json!({ "note": "This is a test event from the Webhooks screen." }),
    }) {
        Ok(b) => b,
        Err(e) => return format!("Could not build the test payload: {e}"),
    };

    let client = match reqwest::blocking::Client::builder().timeout(DELIVERY_TIMEOUT).build() {
        Ok(c) => c,
        Err(e) => return format!("Could not start the request: {e}"),
    };

    let mut req = client
        .post(cfg.url.trim())
        .header("Content-Type", "application/json")
        .header("User-Agent", concat!("DigitalProductFactory/", env!("CARGO_PKG_VERSION")))
        .body(body.clone());
    if !cfg.secret.is_empty() {
        req = req.header("X-DPF-Signature", sign(&cfg.secret, &body));
    }

    match req.send() {
        Ok(r) => {
            let code = r.status().as_u16();
            if r.status().is_success() {
                format!("Delivered \u{2014} the endpoint answered HTTP {code}.")
            } else {
                format!("The endpoint answered HTTP {code}, which is not a success. Check the URL and that it accepts POST.")
            }
        }
        Err(e) if e.is_timeout() => format!("No response within {}s \u{2014} the endpoint is too slow or not reachable.", DELIVERY_TIMEOUT.as_secs()),
        Err(e) if e.is_connect() => "Could not connect to that host. Check the URL is correct and the service is running.".to_string(),
        Err(e) => format!("Request failed: {e}"),
    }
}

fn now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The signature must be the documented HMAC-SHA256 hex, or receivers cannot verify it.
    /// This vector is computed independently with Python's hmac/hashlib, not from this code.
    #[test]
    fn signature_matches_the_reference_implementation() {
        // key "secret", body {"a":1}
        let got = sign("secret", br#"{"a":1}"#);
        assert_eq!(
            got,
            "sha256=aa9e2e3575f5d7098b6caccd790888c36d5fdb63342a73bada2d6a51747a8494",
            "signature drifted from the reference HMAC-SHA256"
        );
    }

    #[test]
    fn a_url_must_have_a_scheme_and_a_host() {
        assert!(validate_url("https://example.com/hook").is_ok());
        assert!(validate_url("http://127.0.0.1:5678/webhook/x").is_ok());
        assert!(validate_url("").is_err());
        assert!(validate_url("example.com/hook").is_err());
        assert!(validate_url("https://").is_err());
    }

    #[test]
    fn a_disabled_webhook_sends_nothing_and_a_bad_event_is_not_sent() {
        let log = std::sync::Arc::new(WebhookLog::default());
        let cfg = WebhookConfig { enabled: false, url: "https://example.com".into(), ..Default::default() };
        dispatch(&cfg, &log, WebhookEvent::ProductGenerated, serde_json::json!({}));
        assert!(log.recent().is_empty(), "a disabled webhook must not record a delivery");

        // enabled but the event is not subscribed
        let cfg2 = WebhookConfig {
            enabled: true,
            url: "https://example.com".into(),
            secret: String::new(),
            events: vec![WebhookEvent::ProductExported.as_str().to_string()],
        };
        dispatch(&cfg2, &log, WebhookEvent::ProductGenerated, serde_json::json!({}));
        assert!(log.recent().is_empty(), "an unsubscribed event must not be sent");
    }

    /// A bad URL must be recorded, not silently dropped — this is what makes the tab honest.
    #[test]
    fn a_malformed_url_is_recorded_with_a_reason() {
        let log = std::sync::Arc::new(WebhookLog::default());
        let cfg = WebhookConfig { enabled: true, url: "not-a-url".into(), ..Default::default() };
        dispatch(&cfg, &log, WebhookEvent::ProductGenerated, serde_json::json!({}));
        let r = log.recent();
        assert_eq!(r.len(), 1);
        assert!(!r[0].ok);
        assert!(r[0].result.contains("http://"), "reason should say what is wrong: {}", r[0].result);
    }

    /// The secret must never leak into the log, which the UI renders.
    #[test]
    fn the_secret_never_appears_in_a_delivery_record() {
        let secret = "super-secret-value-123";
        let log = std::sync::Arc::new(WebhookLog::default());
        let cfg = WebhookConfig {
            enabled: true,
            url: "http://127.0.0.1:9/definitely-not-listening".into(),
            secret: secret.into(),
            events: vec![WebhookEvent::ProductGenerated.as_str().to_string()],
        };
        dispatch(&cfg, &log, WebhookEvent::ProductGenerated, serde_json::json!({}));
        // The worker thread records asynchronously; give it a moment to finish.
        for _ in 0..40 {
            if !log.recent().is_empty() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(50));
        }
        for d in log.recent() {
            assert!(!d.result.contains(secret), "secret leaked into the log: {}", d.result);
            assert!(!d.url.contains(secret));
        }
    }

    #[test]
    fn every_event_has_a_distinct_wire_name_and_a_label() {
        let mut names: Vec<&str> = WebhookEvent::all().iter().map(|e| e.as_str()).collect();
        let n = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), n, "two events share a wire name");
        for e in WebhookEvent::all() {
            assert!(!e.label().is_empty());
        }
    }
}
